### ISSUE TITLE
Implement Display trait on `Tag`, `Frame`, etc?

### ISSUE THREAD

**Issue by danieljrmay** [polyfloyd/rust-id3#37]
Hello,

First of all thank you (and all the other contributors) for such a great crate.

I have written a bit of software in Rust which can examine and play DSF files. I use `rust-id3` to read the ID3v2 tag which can be embedded in them. I have a collection of functions which I use to output a human readable version of `Tag` to the console.  It currently looks like this (with some elisions for clarity):

```
DSF Metadata
…
Fmt chunk:
Channel type = Stereo: FL, FR.
Channel number = 2
Sampling frequency = 2822400 Hz
Bits per sample = 1
Sample count per channel = 648523944
Block size per channel = 4096 bytes
Calculated duration = 00:03:49;2194344 h:min:s;samples
…
ID3Tag:
TALB: Album/Movie/Show title = Acoustic Trio - DSD Sessions
TIT2: Title/songname/content description = Rodeo On A Ridge
TPE1: Lead performer(s)/Soloist(s) = David Elias
TCON: Content type = Independent Acoustic
TYER: Year = 2006
TDAT: Date = 1711
TIME: Time = 1048
APIC: Attached picture = 
	Format: image/jpeg
	Type: Other
	Description: 
	Size: 357673 bytes
```

It occurred to me that this sort of functionality might be useful to other users of `rust-id3`.

However, before I fork `rust-id3` I wanted to ask if you were in principle interested in accepting a pull request which implemented this kind of thing?

To give you and idea of what I am thinking:
1. Implement the `Display` trait on `Tag`, `Frame`, and the relevant structs and enums in the `id3::frame` module.
2. Perhaps add a `name()` method to `Frame` which would return a _human readable_ string for the frame Id. Or this could be done by a stand-alone function e.g. `get_name(id: &str) -> &'static str` where `get_name("TALB")` would return `"Album/Movie/Show title"`, etc.

Obviously the precise format of the string returned by `tag.to_string()` is a bit of a matter of taste (and I am open to suggestions, I have tried to stick to the ID3v2 specs for the names), but having a default `Display` would certainly be useful to me, and perhaps could be useful to others.

However, you may feel that this functionality does not belong in `rust-id3` and is something which is more properly done outside of it.

Let me know what you think and whether you would be interested in looking at a pull request with this sort of thing implemented.

Thank you again and best wishes,

Dan

**Comment by polyfloyd** [comment]
Hey Daniel,

Thank you for your comment :) Let's break it down:

`fmt::Display` is for user facing output. The desired format varies across applications and taste as you mentioned. But if this lib provides a default that satisfies, let's say, 80% of all use cases that is a good thing.

So yes, let's implement `fmt::Display`. But not for all types. E.g. `Tag` can be a really large structure which can not be really represented in a single line. `Frame` already implements `fmt::Display` but only shows the content. Let's change that so it includes a human readable mapping of the ID as you mentioned and move the current implementation to `Content` so people could use.

For `Tag`, instead of implementing `fmt::Display` we could create a function that simply "dumps" the tag to an `io::Write` in a format similar to what you posted.

What are your thoughts on the above? :)

**Comment by danieljrmay** [comment]
Hello,

That all sounds like a very sensible way of doing things! :smile: 

I will go ahead and create a fork and implement something following the principles you outline above. We can then review & revise it until we're all happy!

Cheers, 

Dan

**Comment by danieljrmay** [comment]
Hello,

So I have had a go at implementing the changes we discussed. Here is my first attempt: #38

Let me know what you think.

Best wishes,

Dan
